create table if not exists public.curations (
  id text primary key,
  name text not null,
  curators text not null default '',
  assistants text not null default '',
  a numeric not null default 0,
  b1 numeric not null default 0,
  b2 numeric not null default 0,
  c numeric not null default 0,
  fengyun numeric not null default 0,
  display_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.board_notes (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('todo', 'setting')),
  title text not null,
  body text not null,
  display_order integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.curations enable row level security;
alter table public.board_notes enable row level security;

drop policy if exists "public read curations" on public.curations;
create policy "public read curations"
  on public.curations for select
  using (true);

drop policy if exists "public read board notes" on public.board_notes;
create policy "public read board notes"
  on public.board_notes for select
  using (true);

insert into public.curations
  (id, name, curators, assistants, a, b1, b2, c, fengyun, display_order)
values
  ('niulang-zhinu', '牛郎织女', '欣颍 & 渝恩', '', 0, 0, 0, 0, 0, 1),
  ('menora', 'Menora (泰国）', '民强 & 宇恒', '', 0, 0, 0, 0, 0, 2),
  ('hunli', '婚礼', '珈玮 & 惠翎', '', 0, 0, 0, 0, 0, 3),
  ('baxian-guohai', '八仙过海', '尤歆', '', 0, 0, 0, 0, 0, 4),
  ('parameswara', 'Parameswara', '王通 & 宇翔', '', 0, 0, 0, 0, 0, 5),
  ('change-houyi', '嫦娥奔月/后羿', '惠翎 & 婞荧', '', 0, 0, 0, 0, 0, 6),
  ('sang-kancil', 'Sang Kancil', '杰升 & 凯渲', '', 0, 0, 0, 0, 0, 7),
  ('xiyouji-danaotiangong', '西游记/大闹天宫', '喻萱', '', 0, 0, 0, 0, 0, 8),
  ('niangao', '年糕', '竣铭 & 哲豪 & 家翰', '', 0, 0, 0, 0, 0, 9),
  ('shuihuzhuan-108', '水浒传/108 好汉', '健美', '', 0, 0, 0, 0, 0, 10),
  ('shennong', '神农尝百草', '威祥', '', 0, 0, 0, 0, 0, 11),
  ('dabogong', '大伯公', '采瑩', '', 0, 0, 0, 0, 0, 12),
  ('hanyu', '韩愈的故事', '可薇', '', 0, 0, 0, 0, 0, 13),
  ('sanguoyanyi', '三国演义', '铭轩 & 奕恒', '', 0, 0, 0, 0, 0, 14),
  ('tiangan-dizhi-shengxiao', '天干地支与十二生肖', '祖恩 & 竣铭', '', 0, 0, 0, 0, 0, 15),
  ('hongloumeng', '红楼梦', '雯静 & 素心', '', 0, 0, 0, 0, 0, 16),
  ('chabaixi', '茶百戏', '健美 & 昕莹', '', 0, 0, 0, 0, 0, 17)
on conflict (id) do update set
  name = excluded.name,
  curators = excluded.curators,
  assistants = excluded.assistants,
  a = excluded.a,
  b1 = excluded.b1,
  b2 = excluded.b2,
  c = excluded.c,
  fengyun = excluded.fengyun,
  display_order = excluded.display_order,
  updated_at = now();

insert into public.board_notes (type, title, body, display_order)
select * from (
  values
    ('todo', '补录 B1', '请检查尚未录入的 B1 内部分。', 1),
    ('todo', '复核风云分', '风云加分较高的策展，锁定前需二次确认证据。', 2),
    ('todo', '提醒同侪投票', '尚未提交本月投票的策展，请在月会前完成。', 3),
    ('setting', '公开显示', '排名、总分、A/B/C/风云分、亮点。', 1),
    ('setting', '内部保留', '扣分原因、评语、人工调整记录。', 2),
    ('setting', '发布出口', '网页总榜、WhatsApp 文字、打印月榜。', 3)
) as seed(type, title, body, display_order)
where not exists (select 1 from public.board_notes);
