create table if not exists public.curations (
  id text primary key,
  name text not null,
  curators text not null default '',
  assistants text not null default '',
  a numeric not null default 0,
  b1 numeric not null default 0,
  b2 numeric not null default 0,
  c numeric not null default 0,
  fengyun numeric not null default 0,
  display_order integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.board_notes (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('todo', 'setting')),
  title text not null,
  body text not null,
  display_order integer not null default 0,
  updated_at timestamptz not null default now()
);

alter table public.curations enable row level security;
alter table public.board_notes enable row level security;

drop policy if exists "public read curations" on public.curations;
create policy "public read curations"
  on public.curations for select
  using (true);

drop policy if exists "public read board notes" on public.board_notes;
create policy "public read board notes"
  on public.board_notes for select
  using (true);

insert into public.curations
  (id, name, curators, assistants, a, b1, b2, c, fengyun, display_order)
values
  ('niulang-zhinu', '牛郎织女', '欣颖', '', 28, 15, 7, 30, 120, 1),
  ('menora', 'Menora（泰国）', '民强 & 守恒', '', 30, 10, 8, 28, 60, 2),
  ('hunli', '婚礼', '珈玮 & 惠翎', '', 18, 5, 7, 22, 180, 3),
  ('baishezhuan', '白蛇传', '慧翎', '', 26, 15, 9, 24, 80, 4),
  ('mulan', '花木兰', '凯钲', '', 24, 0, 5, 24, 90, 5),
  ('change', '嫦娥奔月', '可薇', '', 22, 10, 9, 18, 100, 6),
  ('liang-shanbo', '梁山伯与祝英台', '竣铭', '', 25, 10, 6, 20, 50, 7),
  ('mengjiangnu', '孟姜女', '采萤', '', 20, 5, 5, 18, 40, 8),
  ('nezha', '哪吒', '民强', '', 29, 15, 10, 26, 70, 9),
  ('guanyu', '关公', '素岑', '', 27, 10, 6, 24, 60, 10),
  ('mazu', '妈祖', '健美', '', 30, 15, 8, 30, 90, 11),
  ('baosheng', '保生大帝', '喻萱', '', 21, 10, 4, 16, 40, 12),
  ('qixi', '七夕', '惠翎', '', 24, 10, 6, 22, 60, 13),
  ('yuanxiao', '元宵', '凯钲', '', 23, 5, 4, 18, 35, 14),
  ('shadow-puppet', '皮影戏', '可薇', '', 26, 15, 7, 24, 65, 15),
  ('lion-dance', '舞狮', '竣铭', '', 28, 10, 6, 20, 80, 16),
  ('clan-stories', '姓氏故事', '采萤', '', 22, 0, 3, 12, 20, 17)
on conflict (id) do nothing;

insert into public.board_notes (type, title, body, display_order)
select * from (
  values
    ('todo', '补录 B1', '请检查尚未录入的 B1 内部分。', 1),
    ('todo', '复核风云分', '风云加分较高的策展，锁定前需二次确认证据。', 2),
    ('todo', '提醒同侪投票', '尚未提交本月投票的策展，请在月会前完成。', 3),
    ('setting', '公开显示', '排名、总分、A/B/C/风云分、亮点。', 1),
    ('setting', '内部保留', '扣分原因、评语、人工调整记录。', 2),
    ('setting', '发布出口', '网页总榜、WhatsApp 文字、打印月榜。', 3)
) as seed(type, title, body, display_order)
where not exists (select 1 from public.board_notes);
